# Generated by Django 4.0.4 on 2023-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='mobile',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='type',
            new_name='finame',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='lname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='pwd',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
