# Generated by Django 4.0.4 on 2023-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_mobile_recruiter_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
