# Generated by Django 4.0.4 on 2023-04-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_recruiter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='status',
        ),
    ]
