# Generated by Django 4.0.4 on 2023-05-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_studentuser_contact_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='logo',
        ),
    ]
