# Generated by Django 4.0.4 on 2023-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_image_job_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
        migrations.AddField(
            model_name='job',
            name='companyimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
