# Generated by Django 4.0.4 on 2023-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_remove_job_logo_job_companyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='companyimage',
        ),
    ]
