# Generated by Django 4.0.4 on 2023-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
