# Generated by Django 4.0.4 on 2023-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_cname_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
