# Generated by Django 4.0.4 on 2023-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_recruiter_contact_alter_studentuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='pwd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='pwd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
