# Generated by Django 4.2.1 on 2023-06-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='uname',
        ),
    ]
